Added compile-time defines for embedded builds
wolfSSL/wolfPKCS11 pull request #18
Opened 2023-04-18 14:27 UTC by danielinux

- WOLFSSL_USER_SETTINGS to avoid including wolfssl/options.h
- WOLFPKCS11_USER_SETTINGS to avoid including wolfPKCS11/options.h
- NO_PKCS11_TIME to make wc_GetTime() optional (it disables bruteforce protections on token login)

2023-04-23 22:21 UTC, SparkiDev requested changes

2023-04-23 22:21 UTC, SparkiDev commented on src/internal.c
> +        slot->token.soFailedLogin = 0;
Why reset login failures even on failure?

2023-04-23 22:21 UTC, SparkiDev commented on src/internal.c
> +        token->userFailedLogin = 0;
Again here, resetting failed on failure.

2023-07-12 17:33 UTC, danielinux commented on src/internal.c
> +        slot->token.soFailedLogin = 0;
Yikes. I've now moved this to the #else case (so when `WOLFPKCS11_NO_TIME` is defined), to disable the failure counter.

2023-07-12 17:33 UTC, danielinux commented on src/internal.c
> +        token->userFailedLogin = 0;
see above

2023-07-12 19:35 UTC, dgarske approved these changes

2023-07-12 21:21 UTC, SparkiDev approved these changes

2023-07-12 21:21 UTC, merged