PKCS11 TPM support (RSA only)
wolfSSL/wolfPKCS11 pull request #23
Opened 2023-11-13 17:38 UTC by dgarske

TODO: KeyStore using TPM NV

2023-11-30 00:31 UTC, SparkiDev submitted a review, later dismissed

2023-12-05 18:36 UTC, dgarske commented
@SparkiDev this is ready for your review and finalization. I'll followup with any portability issues in a new PR.

2023-12-05 21:27 UTC, SparkiDev requested changes

2023-12-05 21:27 UTC, SparkiDev commented on src/internal.c
> +            maxSz = -1;
BAD_FUNC_ARG?

2023-12-05 21:27 UTC, SparkiDev commented on src/internal.c
> +    if (slot == NULL) return;
return on next line

2023-12-05 21:27 UTC, SparkiDev commented on src/internal.c
> +        if (ret == 0) {
'ret == 0' checks look wrong

2023-12-05 22:04 UTC, SparkiDev approved these changes

2023-12-05 22:05 UTC, merged