Examples: added some useful examples
wolfSSL/wolfPKCS11 pull request #34
Opened 2024-10-31 23:11 UTC by SparkiDev

2024-11-01 16:37 UTC, dgarske requested changes

2024-11-01 16:37 UTC, dgarske commented on examples/add_rsa_key_file.c
> +        len = XFREAD(buffer, 1, sizeof(buffer), file);
```examples/add_rsa_key_file.c:161:15: error: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Werror,-Wshorten-64-to-32]
  161 |         len = XFREAD(buffer, 1, sizeof(buffer), file);
      |             ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/wolfssl/wolfcrypt/wc_port.h:771:24: note: expanded from macro 'XFREAD'
  771 |     #define XFREAD     fread
      |                        ^```

2024-11-01 16:37 UTC, dgarske commented on .gitignore
> +examples/add_aes_key
Can you add documentation for how to use these? Or maybe even a script that runs them so we can add to the CI?

2024-11-04 05:47 UTC, SparkiDev commented on .gitignore
> +examples/add_aes_key
Added REAME.md in examples.
Added examples.test in examples.

2024-11-04 18:38 UTC, dgarske approved these changes

2024-11-04 18:45 UTC, merged