Add support for AES-CCM.
wolfSSL/wolfPKCS11 pull request #37
Opened 2024-12-05 22:20 UTC by anhu

Unit test created and passed.

2024-12-06 20:51 UTC, JacobBarthelmeh requested changes
Have a small comment about the configure.ac setup. Rest looks good, thanks!

2024-12-06 20:51 UTC, JacobBarthelmeh commented on configure.ac
> +echo "   * AES-CCM:                    $ENABLED_AESCCM"
There is a aesgcm flag, please add a matching aesccm flag for optionally disabling CCM support.

2024-12-06 20:51 UTC, JacobBarthelmeh commented on configure.ac
> +echo "   * AES-CCM:                    $ENABLED_AESCCM"
When building linked to wolfssl configured with --enable-all I see this output:

```
   * AES-GCM:                    yes
   * AES-CCM:                    
   * MD5:                        yes
```

Looks like the ENABLED_AESCCM value does not get set.

2024-12-11 02:26 UTC, anhu commented on configure.ac
> +echo "   * AES-CCM:                    $ENABLED_AESCCM"
Originally, I had added a flag but I realized that it would be better to go off of wolfSSL's flag. That is how we do it in wolfSSH.  Its great because then if you disable ccm in wolfSSL and then enable it here, you'll get an error. Simply following wolfSSL guarantees no error.  Better customer experience. I'll remove the output of  `* AES-CCM: `

2024-12-17 04:57 UTC, douzzer requested changes
It's super-confusing having the wolfPKCS11 `configure` give the developer control of, and status of, all of the supported ciphers+modes except for AES-CCM.  There should be a `--enable-aesccm` and `* AES-CCM:    yes` (or no) as for the others, else devs will wonder where CCM is, or if there's something special about CCM.

Unrelated to the above, and probably unrelated to the PR, but reproducible when built with current wolfssl `master`:
```
tests/pkcs11test.c:4650 - Get Attributes EC private key params length - FAIL
```
```
tests/pkcs11mtt.c:3644 - Get Attributes EC private key params length - FAIL
```

2025-01-02 22:51 UTC, douzzer approved these changes

2025-01-02 22:52 UTC, merged